FROM node:14-alpine as build-stage
WORKDIR /app
ENV NODE_ENV production
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80:80